version: '3'
services:
  web1:
    image: pratheesh/nginx:V1
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
  web2:
    image: pratheesh/nginx:V1
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
