version: '3'
services:

  web:
    image: pratheeshg/nginx:V1
    ports:
      - "8001:80"
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./www:/var/www/
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

